//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebs.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WSTituloSoap")]
    public interface WSTituloSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTituloSoapChannel : ClienteWebs.ServiceReference3.WSTituloSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTituloSoapClient : System.ServiceModel.ClientBase<ClienteWebs.ServiceReference3.WSTituloSoap>, ClienteWebs.ServiceReference3.WSTituloSoap {
        
        public WSTituloSoapClient() {
        }
        
        public WSTituloSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTituloSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTituloSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTituloSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha) {
            return base.Channel.Agregar(Codigo, Nombre, Tipo, Pub, Precio, Advance, Royalty, Ytd, Notas, Fecha);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha) {
            return base.Channel.AgregarAsync(Codigo, Nombre, Tipo, Pub, Precio, Advance, Royalty, Ytd, Notas, Fecha);
        }
        
        public string[] Actualizar(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha) {
            return base.Channel.Actualizar(Codigo, Nombre, Tipo, Pub, Precio, Advance, Royalty, Ytd, Notas, Fecha);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Tipo, string Pub, string Precio, string Advance, string Royalty, string Ytd, string Notas, string Fecha) {
            return base.Channel.ActualizarAsync(Codigo, Nombre, Tipo, Pub, Precio, Advance, Royalty, Ytd, Notas, Fecha);
        }
        
        public string[] Eliminar(string Codigo) {
            return base.Channel.Eliminar(Codigo);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string Codigo) {
            return base.Channel.EliminarAsync(Codigo);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
