//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebs.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WSAutorSoap")]
    public interface WSAutorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAutorSoapChannel : ClienteWebs.ServiceReference2.WSAutorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAutorSoapClient : System.ServiceModel.ClientBase<ClienteWebs.ServiceReference2.WSAutorSoap>, ClienteWebs.ServiceReference2.WSAutorSoap {
        
        public WSAutorSoapClient() {
        }
        
        public WSAutorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAutorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAutorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAutorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] Agregar(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato) {
            return base.Channel.Agregar(Codigo, Nombre, Apellido, Celular, Direccion, Ciudad, Estado, CodPostal, Contrato);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato) {
            return base.Channel.AgregarAsync(Codigo, Nombre, Apellido, Celular, Direccion, Ciudad, Estado, CodPostal, Contrato);
        }
        
        public string[] Actualizar(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato) {
            return base.Channel.Actualizar(Codigo, Nombre, Apellido, Celular, Direccion, Ciudad, Estado, CodPostal, Contrato);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string Codigo, string Nombre, string Apellido, string Celular, string Direccion, string Ciudad, string Estado, string CodPostal, string Contrato) {
            return base.Channel.ActualizarAsync(Codigo, Nombre, Apellido, Celular, Direccion, Ciudad, Estado, CodPostal, Contrato);
        }
        
        public string[] Eliminar(string Codigo) {
            return base.Channel.Eliminar(Codigo);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string Codigo) {
            return base.Channel.EliminarAsync(Codigo);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
